### ISSUE TITLE
Terminal is frozen when switching network

### ISSUE THREAD

**Issue by tnhu** [gravitational/teleconsole#18] opened 2017-01-26 07:02 UTC
After joining a session, I switch my wireless network. Teleconsole's terminal is frozen immediately.

It should retry to connect, or quit the session so I can reconnect manually.

**Comment by kontsevoy** [comment] 2017-01-27 03:28
@tnhu thank you for reporting this. It has actually been fixed in Teleport (SSH library Teleconsole uses) and will get vendored in during next Teleport release (in a few weeks).

**Comment by kontsevoy** [comment] 2017-02-02 20:19
dupe of #16

**Closed as completed by kontsevoy** 2017-02-02 20:19 UTC
